name: DungeonRealmsLoby
main: net.dungeonrealms.lobby.DungeonRealms
version: ${project.parent.version}
authors: [apollosoftware, Bradez1571, EtherealTemplar, iFamasssxD, Proxying, Xwaffle]
website: http://www.dungeonrealms.net
depend: [WorldGuard, BossBarAPI, ProtocolLib]
description: The new and improved DungeonRealms!