name: DR-Lobby
main: net.dungeonrealms.lobby.ServerLobby
version: ${project.parent.version}
authors: [apollosoftware, Vawke]
website: http://www.dungeonrealms.net
depend: [BossBarAPI, ProtocolLib]
description: The new and improved DungeonRealms!