name: DungeonRealms
main: DungeonRealms
version: 1.0
authors: [apollosoftware, Bradez1571, EtheralTemplar, iFamasssxD, Proxying, Xwaffle]
website: http://www.dungeonrealms.net
depend: [TitleAPI, WorldGuard, BossBarAPI, ProtocolLib]
description: The new and improved DungeonRealms!