name: DungeonRealms
main: net.dungeonrealms.vgame.Game
version: ${project.parent.version}
authors: [Vawke, Atlas__]
website: http://www.dungeonrealms.net
depend: [WorldGuard, BossBarAPI, ProtocolLib, BungeeTabListPlus]
description: The new and improved DungeonRealms!