name: DungeonRealms
main: net.dungeonrealms.DungeonRealms
version: ${project.parent.version}
authors: [apollosoftware, Bradez1571, EtherealTemplar, Proxying, Xwaffle]
website: http://www.dungeonrealms.net
depend: [WorldGuard, BossBarAPI, ProtocolLib, BungeeTabListPlus]
description: The new and improved DungeonRealms!